services:
  storage_sync:
    build:
      context: .
      dockerfile: services/storage_sync/Dockerfile
    environment:
      - TZ=Europe/Berlin
      - LANG=en_US.UTF-8
    volumes:
      - storage:/mnt/pufferpanel
    tty: true
    restart: unless-stopped

  panel:
    build:
      context: .
      dockerfile: services/panel/Dockerfile
    environment:
      - TZ=Europe/Berlin
      - LANG=en_US.UTF-8
    volumes:
      - storage:/var/lib/pufferpanel
    ports:
      - 8080:8080
      - 5657:5657
      - 25565:25565
    tty: true
    depends_on:
      - storage_sync
    restart: unless-stopped


volumes:
  storage: