services:
  remote_storage_sync:
    build:
      context: .
      dockerfile: services/remote_storage_sync/Dockerfile
    environment:
      - TZ=Europe/Berlin
      - LANG=en_US.UTF-8
    volumes:
      - storage:/mnt/pufferpanel
    tty: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "[ -f /mnt/pufferpanel/.sync_bootstrap_complete ]"]
      timeout: 3s
      interval: 10s
      retries: 360

  panel:
    build:
      context: .
      dockerfile: services/panel/Dockerfile
    environment:
      - TZ=Europe/Berlin
      - LANG=en_US.UTF-8
    volumes:
      - storage:/var/lib/pufferpanel
    ports:
      - 8080:8080
      - 5657:5657
      - 25565:25565
    tty: true
    depends_on:
      remote_storage_sync:
        condition: service_healthy
    restart: unless-stopped


volumes:
  storage: